name: 🐛 Bug Report
description: Report a bug or issue with SyncBoost
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve the issue.
        
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-Flight Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of SyncBoost
          required: true
        - label: I have tried `/syncboost reload` to rule out configuration issues
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Start the server with...
        2. Run command...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: input
    id: syncboost-version
    attributes:
      label: SyncBoost Version
      description: Run `/syncboost` and check the GUI title or check the jar filename
      placeholder: "e.g., 1.2.1"
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What Minecraft version are you running?
      placeholder: "e.g., 1.21.4"
    validations:
      required: true

  - type: input
    id: server-software
    attributes:
      label: Server Software
      description: What server software and version are you using?
      placeholder: "e.g., Paper 1.21.4 build 123"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Run `java -version` in your terminal
      placeholder: "e.g., Java 21.0.1"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs / Stack Trace
      description: |
        Please paste any relevant error messages or stack traces.
        **Tip:** Use code blocks (```) for better formatting
      placeholder: Paste your console output here
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration Files
      description: If relevant, paste your config.yml or specific module configuration
      placeholder: Paste your config here
      render: yaml

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (plugins installed, server setup, etc.)
